### ISSUE TITLE
Collections: Should not use `has_key` because generic mappings do not have it

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#1479]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=1479) by CBPham on 17 Jun 2013_

Using with the RequestsLibrary, I had a keyword:

Dictionary Should Contain Key     ${resp.headers}   1234 

This used to work fine with 2.7.7 but after upgrading 2.8.x I am getting the following error:

21:07:31.509    FAIL    AttributeError: 'CaseInsensitiveDict' object has no attribute 'has_key'
21:07:31.509    DEBUG   Traceback (most recent call last): File "/Library/Python/2.7/site-packages/robot/libraries/Collections.py", line 567, in dictionary_should_contain_key _verify_condition(dictionary.has_key(key), default, msg)

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=1479#c2) by @pekkaklarck on 21 Aug 2013_

I looked at this noticed that CaseInsensitiveDict in requests used to be based on dict but is nowadays based on MutableMapping. I also learned that MutableMapping and Mapping don't have `has_key`, only `__contains__`:
<a href="http://docs.python.org/2/library/collections.html#collections-abstract-base-classes" rel="nofollow">http://docs.python.org/2/library/collections.html#collections-abstract-base-classes</a>

It's best that we stop using `mapping.has_key(key)` altogether in favor of `key in mapping`. We already use the latter, more Pythonic version, in most places so this shouldn't be a big task.
