### ISSUE TITLE
Removed utility functions broke SSHLibrary and SeleniumLibrary and need to be added back

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#1472]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=1472) by aalto.tatu on 12 Jun 2013_

I have simple test that logins to server and uses Get File keyword to retrieve a file. Basically it looks like this: 
ssh library get
    Open Connection    &lt;ip goes here&gt;
    Login    username    password
    Get File    /tmp/config.tar.gz    /tmp/config-server-01.tar.gz
    [Teardown]    Close All Connections

No in RF version 2.7.7 this did work like a charm but in RF version 2.8 I get error: 

&lt;kw type="kw" name="SSHLibrary.Get File"&gt;
&lt;doc&gt;Copies file(s) from remote host to local host.&lt;/doc&gt;
&lt;arguments&gt;
&lt;arg&gt;/tmp/config.tar.gz&lt;/arg&gt;
&lt;arg&gt;/tmp/config-server-01.tar.gz&lt;/arg&gt;
&lt;/arguments&gt;
&lt;msg timestamp="20130613 09:34:21.249" level="INFO"&gt;[chan 3] Opened sftp connection (server version 3)&lt;/msg&gt;
&lt;msg timestamp="20130613 09:34:21.281" level="FAIL"&gt;AttributeError: 'module' object has no attribute 'matches'&lt;/msg&gt;
&lt;status status="FAIL" endtime="20130613 09:34:21.281" starttime="20130613 09:34:21.222"&gt;&lt;/status&gt;
&lt;/kw&gt;

Reproduced in linux with pybot version 2.8 and it works with version 2.7.7.
