### ISSUE TITLE
Failures at random with the exception "AttributeError: 'VariableError' object has no attribute 'skip'"

### ISSUE THREAD

**Issue by tminakov** [robotframework/robotframework#4061]
After upgrading to v4.0 - and currently at v4.1 - an execution of a set of cases fails with this exception, at random places:

`AttributeError: 'VariableError' object has no attribute 'skip'`

Executing the case where it failed, or the suite **does not** reproduce the error; it happens at seemingly random places (cases), that have been passing for years - e.g. I do not have a reproducible case, and do not know how to cause the issue.

When the exception occurs the execution stops abruptly.

---

The stack trace when it fails:
```
Unexpected error: AttributeError: 'VariableError' object has no attribute 'skip'
Traceback (most recent call last):
  File "/home/the-local-user/.local/lib/python3.8/site-packages/robot/utils/application.py", line 83, in _execute
    rc = self.main(arguments, **options)
  File "/home/the-local-user/.local/lib/python3.8/site-packages/robot/run.py", line 450, in main
    result = suite.run(settings)
  File "/home/the-local-user/.local/lib/python3.8/site-packages/robot/running/model.py", line 296, in run
    self.visit(runner)
  File "/home/the-local-user/.local/lib/python3.8/site-packages/robot/model/testsuite.py", line 226, in visit
    visitor.visit_suite(self)
  File "/home/the-local-user/.local/lib/python3.8/site-packages/robot/model/visitor.py", line 87, in visit_suite
    suite.suites.visit(self)
  File "/home/the-local-user/.local/lib/python3.8/site-packages/robot/model/itemlist.py", line 77, in visit
    item.visit(visitor)
  File "/home/the-local-user/.local/lib/python3.8/site-packages/robot/model/testsuite.py", line 226, in visit
    visitor.visit_suite(self)
  File "/home/the-local-user/.local/lib/python3.8/site-packages/robot/model/visitor.py", line 87, in visit_suite
    suite.suites.visit(self)
  File "/home/the-local-user/.local/lib/python3.8/site-packages/robot/model/itemlist.py", line 77, in visit
    item.visit(visitor)
  File "/home/the-local-user/.local/lib/python3.8/site-packages/robot/model/testsuite.py", line 226, in visit
    visitor.visit_suite(self)
  File "/home/the-local-user/.local/lib/python3.8/site-packages/robot/model/visitor.py", line 87, in visit_suite
    suite.suites.visit(self)
  File "/home/the-local-user/.local/lib/python3.8/site-packages/robot/model/itemlist.py", line 77, in visit
    item.visit(visitor)
  File "/home/the-local-user/.local/lib/python3.8/site-packages/robot/model/testsuite.py", line 226, in visit
    visitor.visit_suite(self)
  File "/home/the-local-user/.local/lib/python3.8/site-packages/robot/model/visitor.py", line 88, in visit_suite
    suite.tests.visit(self)
  File "/home/the-local-user/.local/lib/python3.8/site-packages/robot/model/itemlist.py", line 77, in visit
    item.visit(visitor)
  File "/home/the-local-user/.local/lib/python3.8/site-packages/robot/model/testcase.py", line 130, in visit
    visitor.visit_test(self)
  File "/home/the-local-user/.local/lib/python3.8/site-packages/robot/running/suiterunner.py", line 161, in visit_test
    self._run_teardown(test.teardown, status, result)
  File "/home/the-local-user/.local/lib/python3.8/site-packages/robot/running/suiterunner.py", line 198, in _run_teardown
    status.teardown_executed(exception)
  File "/home/the-local-user/.local/lib/python3.8/site-packages/robot/running/status.py", line 98, in teardown_executed
    if failure.skip:
```

I'm attaching the last hundred lines of an output.xml of the most recent failure.
[output.zip](https://github.com/robotframework/robotframework/files/6991298/output.zip)

Versions:
robotframework 4.1
robotframework-pythonlibcore 2.2.1
python 3.8.5

**Comment by pekkaklarck** [comment]
Thanks for the report. This is easy to reproduce with the following example:
```robotframework
*** Test Cases ***
Example
    No Operation
    [Teardown]    ${nonex}
```

**Comment by tminakov** [comment]
Thank you! Hopefully, with a clear reproducible path a fix is in sight?

**Comment by pekkaklarck** [comment]
Fixed now. It's about time for RF 4.1.1 also otherwise. I try to get a release candidate out this or next week so that fixes can be still tested easily in real environments before the final release.
