### ISSUE TITLE
Executing run multiple times on RobotRunner fails

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#881]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=881) by imranoftherings on 19 Jun 2011_

To try to save the time of RobotRunner instance creation, I create RobotRunner once. The I reuse the same instance of the RobotRunner object to run test suites.

First time execution works fine in 2.6 alpha. Executing run a second time fails with

[ ERROR ] Unexpected error: AttributeError: RunnableTestSuite instance has no attribute 'remove_keywords'

Developers use RF for testing their changes locally. So we usually we have users who execute one test suite at a time. The cost of RobotRunner instance creation every time is prohibitive and infact much higher than the actual test execution time.

This worked fine with 2.5.7
