### ISSUE TITLE
remoteapplications can not work in RF2.7

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#1098]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=1098) by renxingwei on 22 Mar 2012_

When I ues remoteapplications and SwingLibrary testing JAVA GUI in RF2.7,remoteapplications can not be imported.But I use RF 2.5.7,it can work.
python:2.6.6
jython:2.5.1
RF:2.7
os: windows xp pro sp2

Error in file 'E:\ISMV1R10Applet\resources\common.tsv' in table 'Setting': Importing test library 'RemoteApplications' failed: ImportError: cannot import name NAMESPACES
Traceback (most recent call last):
  File "E:\ISMV1R10Applet\lib\RemoteApplications.py", line 24, in &lt;module&gt;
    from robot.running import NAMESPACES
PYTHONPATH:
  C:\Python26\Lib\site-packages\robot\libraries
  C:\Python26\Lib\site-packages
  C:\jython2.5.1\Lib
  **classpath**
  **pyclasspath**/
  C:\jython2.5.1\Lib\site-packages
