### ISSUE TITLE
Messages in test body cause crash when using templates and some iterations are skipped

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#5326]
This is a regression causes by #4426. The root cause is this code that handles the situation where all iterations have been skipped:
```python
if all(item.skipped for item in result.body):
    raise ExecutionFailed('All iterations skipped.', skip=True)
```
This code works fine normally, but if `result.body` contains messages, it fails with this error:
```
AttributeError: 'Message' object has no attribute 'skipped'
```
Luckily tests having messages directly in their body is rare. I think the only way that could happen is when using a listener that logs something in `start_test` or if results are modified programmatically. Crashes are nevertheless always bad, and based on a thread on our Slack someone had encountered this issue, so this requires a pretty high severity.

**Comment by pekkaklarck** [comment]
Apparently the DataDriver tool logs its configuration so that the message goes directly to test body. That makes the situation pretty common, but I don't think it still warrants an immediate bug fix release. We'll probably release RF 7.2.1 with this and some other fixes next week or the week after.
